CREATE TABLE transactions (
	id NUMBER NOT NULL PRIMARY KEY,
	description VARCHAR2(100) NOT NULL,
	tdate DATE NOT NULL,
	type VARCHAR2(10) NOT NULL,
	value DECIMAL(10, 2) NOT NULL
);

CREATE SEQUENCE sq_transaction INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE ORDER;

COMMIT;